spring.application.name=NOTIFICATION-SERVICE

server.port=${server-port}

# Consumer Configuration (Reading / Ingestion)
spring.kafka.consumer.bootstrap-servers=${kafka-consumer-host}
spring.kafka.consumer.group-id=${consumer-group-id}
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.consumer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer


## db configuration
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=${jdbc-url}
spring.datasource.username=${datasource-username}
spring.datasource.password=${datasource-password}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql= true

eureka.instance.client.serviceUrl.defaultZone=${eureka-server-url}
