spring.application.name=USER-SERVICE
server.port=${server-port}

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=${jdbc-url}
spring.datasource.username=${datasource-username}
spring.datasource.password=${datasource-password}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql= true

eureka.instance.client.serviceUrl.defaultZone=${eureka-server-url}