spring.application.name=PAYMENT-SERVICE
server.port=${server-port}
stripe.secret.key=${stripe-api-key}
stripe.publishable.key=${stripe-publishable-key}
webhook.secret=${webhook-secret}
api.gateway-url=${api-gateway-url}

eureka.instance.client.serviceUrl.defaultZone=${eureka-server-url}
app.frontend-url=${frontend-url}
##db config
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=${jdbc-url}
spring.datasource.username=${datasource-username}
spring.datasource.password=${datasource-password}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql= true
