spring.application.name=EVENT-SERVICE
server.port=${server-port}

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=${jdbc-url}spring.datasource.username=${datasource-username}
spring.datasource.password=${datasource-password}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql= true

eureka.instance.client.serviceUrl.defaultZone=${eureka-server-url} 

spring.data.redis.host=${redis-host}
spring.data.redis.port=${redis-port}
spring.data.redis.timeout=5000


spring.data.redis.jedis.pool.max-active=10
spring.data.redis.jedis.pool.max-idle=5
spring.data.redis.jedis.pool.min-idle=2
spring.data.redis.jedis.pool.max-wait=20





# Producer Configuration (Publishing / Outbound)
spring.kafka.producer.bootstrap-servers=${kafka-server}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
